# Image de base : nginx
# copier default.conf dans : /etc/nginx/conf.d/default.conf
# Fichier HTML pour réponses BACKEND-NOT-FOUND : à copier dans /var/www/html/backend-not-found.html
# Configuration du proxy : copier proxy.conf dans /etc/nginx/includes/
